export const CHANGE_SEARCH_FIELD        = 'CHANGE_SEARCH_FIELD';

export const REQEUST_ROBOTS_PENDING     = 'REQEUST_ROBOTS_PENDING';
export const REQEUST_ROBOTS_SUCCESSS    = 'REQEUST_ROBOTS_SUCCESSS';
export const REQEUST_ROBOTS_FAILED      = 'REQEUST_ROBOTS_FAILED';
